#if !defined(AFX_AXSIMPLEDATAGRID_H__C0D171FE_457B_4834_AC2C_D0E75ED02444__INCLUDED_)
#define AFX_AXSIMPLEDATAGRID_H__C0D171FE_457B_4834_AC2C_D0E75ED02444__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAxSimpleDataGrid wrapper class

class CAxSimpleDataGrid : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAxSimpleDataGrid)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfe10bf68, 0xb99d, 0x4982, { 0xa1, 0xec, 0x6, 0x7c, 0x0, 0xff, 0xdd, 0xa2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long ConnectBYUDL(LPCTSTR szUDLFileName);
	long SetQuery(LPCTSTR szQuery);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXSIMPLEDATAGRID_H__C0D171FE_457B_4834_AC2C_D0E75ED02444__INCLUDED_)
