//
//	ConstDatasourceProps.h
//
//	Copyright (C) Pete Cooke 14/11/2003 21:02:32
//
//#include "ConstDatasourceProps.h" //namespace CONS_DS_PROPS
//using namespace CONS_DS_PROPS::PROPERTY_ORDINALS;
//

#pragma once

namespace CONS_DS_PROPS{

	class _CONS_DS_PROPS{};

	namespace PROPERTY_ORDINALS{

		class _CONS_DS_PROPS_PROPERTY_ORDINALS{};

		typedef enum _ePROPERTY_ORDINAL{
			iPO_ACTIVESESSIONS			= 0
			, iPO_ASYNCTXNABORT
			, iPO_ASYNCTXNCOMMIT
			, iPO_BYREFACCESSORS
			, iPO_CATALOGLOCATION
			, iPO_CATALOGTERM
			, iPO_COLUMNDEFINITION
			, iPO_CONCATNULLBEHAVIOR
			, iPO_DATASOURCE_TYPE
			, iPO_DATASOURCENAME
			, iPO_DATASOURCEREADONLY
			, iPO_DBMSNAME
			, iPO_DBMSVER
			, iPO_DSOTHREADMODEL
			, iPO_GROUPBY
			, iPO_HETEROGENEOUSTABLES
			, iPO_IDENTIFIERCASE
			, iPO_MAXINDEXSIZE
			, iPO_MAXOPENCHAPTERS
			, iPO_MAXROWSIZE
			, iPO_MAXROWSIZEINCLUDESBLOB
			, iPO_MAXTABLESINSELECT
			, iPO_MULTIPLEPARAMSETS
			, iPO_MULTIPLERESULTS
			, iPO_MULTIPLESTORAGEOBJECTS
			, iPO_MULTITABLEUPDATE
			, iPO_NULLCOLLATION
			, iPO_OLEOBJECTS
			//, iPO_OPENROWSETSUPPORT			//Not VC6
			, iPO_ORDERBYCOLUMNSINSELECT
			, iPO_OUTPUTPARAMETERAVAILABILITY
			, iPO_PERSISTENTIDTYPE
			, iPO_PREPAREABORTBEHAVIOR
			, iPO_PROCEDURETERM
			, iPO_PROVIDERFILENAME
			, iPO_PROVIDERFRIENDLYNAME 
			, iPO_PROVIDERMEMORY 
			, iPO_PROVIDEROLEDBVER
			, iPO_PROVIDERVER 
			, iPO_QUOTEDIDENTIFIERCASE
			//, iPO_ROWSETCONVERSIONCOMMAND
			, iPO_SERVERNAME
			, iPO_SQLSUPPORT
			, iPO_STRUCTUREDSTORAGE
			, iPO_SUBQUERIES
			, iPO_SUPPORTEDTXNDDL
			, iPO_SUPPORTEDTXNISOLEVELS
			, iPO_SUPPORTEDTXNISORETAIN
			, iPO_TABLETERM
			, iPO_USERNAME
			, iPO__LAST
		} ePROPERTY_ORDINAL;

		const DWORD dwPROPERTY_IDS[ iPO__LAST ] = {
									DBPROP_ACTIVESESSIONS
									, DBPROP_ASYNCTXNABORT
									, DBPROP_ASYNCTXNCOMMIT
									, DBPROP_BYREFACCESSORS
									, DBPROP_CATALOGLOCATION
									, DBPROP_CATALOGTERM
									, DBPROP_COLUMNDEFINITION
									, DBPROP_CONCATNULLBEHAVIOR
									, DBPROP_DATASOURCE_TYPE
									, DBPROP_DATASOURCENAME
									, DBPROP_DATASOURCEREADONLY
									, DBPROP_DBMSNAME
									, DBPROP_DBMSVER
									, DBPROP_DSOTHREADMODEL
									, DBPROP_GROUPBY
									, DBPROP_HETEROGENEOUSTABLES
									, DBPROP_IDENTIFIERCASE
									, DBPROP_MAXINDEXSIZE
									, DBPROP_MAXOPENCHAPTERS
									, DBPROP_MAXROWSIZE
									, DBPROP_MAXROWSIZEINCLUDESBLOB
									, DBPROP_MAXTABLESINSELECT
									, DBPROP_MULTIPLEPARAMSETS
									, DBPROP_MULTIPLERESULTS
									, DBPROP_MULTIPLESTORAGEOBJECTS
									, DBPROP_MULTITABLEUPDATE
									, DBPROP_NULLCOLLATION
									, DBPROP_OLEOBJECTS
									//, DBPROP_OPENROWSETSUPPORT		//Not VC6
									, DBPROP_ORDERBYCOLUMNSINSELECT
									, DBPROP_OUTPUTPARAMETERAVAILABILITY
									, DBPROP_PERSISTENTIDTYPE
									, DBPROP_PREPAREABORTBEHAVIOR
									, DBPROP_PROCEDURETERM
									, DBPROP_PROVIDERFILENAME
									, DBPROP_PROVIDERFRIENDLYNAME 
									, DBPROP_PROVIDERMEMORY 
									, DBPROP_PROVIDEROLEDBVER
									, DBPROP_PROVIDERVER 
									, DBPROP_QUOTEDIDENTIFIERCASE
									//, DBPROP_ROWSETCONVERSIONCOMMAND
									, DBPROP_SERVERNAME
									, DBPROP_SQLSUPPORT
									, DBPROP_STRUCTUREDSTORAGE
									, DBPROP_SUBQUERIES
									, DBPROP_SUPPORTEDTXNDDL
									, DBPROP_SUPPORTEDTXNISOLEVELS
									, DBPROP_SUPPORTEDTXNISORETAIN
									, DBPROP_TABLETERM
									, DBPROP_USERNAME
								};

		const TCHAR szPROPERTY_NAMES[ iPO__LAST ] [ 40 ] = {
									_T("ACTIVE SESSIONS")
									, _T("ASYNC TXN ABORT")
									, _T("ASYNC TXN COMMIT")
									, _T("BYREF ACCESSORS")
									, _T("CATALOG LOCATION")
									, _T("CATALOG TERM")
									, _T("COLUMN DEFINITION")
									, _T("CONCATNULL BEHAVIOR")
									, _T("DATASOURCE_TYPE")
									, _T("DATASOURCE NAME")
									, _T("DATASOURCE READONLY")
									, _T("DBMS NAME")
									, _T("DBMS VER")
									, _T("DSO THREAD MODEL")
									, _T("GROUP BY")
									, _T("HETEROGENEOUS TABLES")
									, _T("IDENTIFIER CASE")
									, _T("MAX INDEX SIZE")
									, _T("MAX OPEN CHAPTERS")
									, _T("MAX ROW SIZE")
									, _T("MAX ROW SIZE INCLUDES BLOB")
									, _T("MAX TABLES IN SELECT")
									, _T("MULTIPLE PARAM SETS")
									, _T("MULTIPLE RESULTS")
									, _T("MULTIPLE STORAGE OBJECTS")
									, _T("MULTI TABLE UPDATE")
									, _T("NULL COLLATION")
									, _T("OLE OBJECTS")
									//, _T("OPEN ROWSET SUPPORT")			//Not VC6
									, _T("ORDER BY COLUMNS IN SELECT")
									, _T("OUTPUT PARAMETER AVAILABILITY")
									, _T("PERSISTENT ID TYPE")
									, _T("PREPARE ABORT BEHAVIOR")
									, _T("PROCEDURE TERM")
									, _T("PROVIDER FILE NAME")
									, _T("PROVIDER FRIENDLY NAME ")
									, _T("PROVIDER MEMORY ")
									, _T("PROVIDER OLEDB VER")
									, _T("PROVIDER VER ")
									, _T("QUOTED IDENTIFIER CASE")
									//, _T("ROWSETCONVERSIONCOMMAND")
									, _T("SERVER NAME")
									, _T("SQL SUPPORT")
									, _T("STRUCTURED STORAGE")
									, _T("SUBQUERIES")
									, _T("SUPPORTED TXN DDL")
									, _T("SUPPORTED TXN ISO LEVELS")
									, _T("SUPPORTED TXN ISO RETAIN")
									, _T("TABLE TERM")
									, _T("USER NAME")
								};

	}//end of namespace PROPERTY_ORDINALS


}//end of namespace CONS_DS_PROPS

/*
	DBPROPSET_DATASOURCEINFO
	Some Properties:

		DBPROP_CATALOGLOCATION
		DBPROP_DATASOURCENAME
		DBPROP_DATASOURCEREADONLY
		DBPROP_DATASOURCE_TYPE
		DBPROP_DBMSNAME
		DBPROP_DBMSVER
		DBPROP_IDENTIFIERCASE
		DBPROP_MAXINDEXSIZE
		DBPROP_MAXOPENCHAPTERS
		DBPROP_MAXROWSIZE
		DBPROP_MAXROWSIZEINCLUDESBLOB
		DBPROP_MAXTABLESINSELECT
		DBPROP_MULTIPLEPARAMSETS
		DBPROP_MULTIPLERESULTS
		DBPROP_MULTIPLESTORAGEOBJECTS
		DBPROP_MULTITABLEUPDATE
		DBPROP_OLEOBJECTS
		DBPROP_OPENROWSETSUPPORT
		DBPROP_ORDERBYCOLUMNSINSELECT
		DBPROP_OUTPUTPARAMETERAVAILABILITY
		DBPROP_PERSISTENTIDTYPE
		DBPROP_PROVIDERFRIENDLYNAME 
		DBPROP_PROVIDERMEMORY 
		DBPROP_PROVIDERFILENAME 
		DBPROP_PROVIDEROLEDBVER 
		DBPROP_PROVIDERVER 
		DBPROP_SERVERNAME
		DBPROP_SQLSUPPORT
		DBPROP_STRUCTUREDSTORAGE
		DBPROP_SUBQUERIES
		DBPROP_USERNAME
*/