//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Project File Assembler.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PROJECTFILEASSEMBLER_DIALOG 102
#define IDR_PROJECTFILEASSEMBLER        103
#define IDD_PAGE_BATCH_FILES            107
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BUILD                129
#define IDD_DLG_HELP                    130
#define IDD_PAGE_INSTALLSHIELD          131
#define IDR_MNU_CTXT_PFADATA            131
#define IDD_PAGE_PFA_DATA               132
#define IDD_PAGE_STEP_TYPE              133
#define IDD_DLG_STRING_REQUESTER        134
#define IDD_PAGE_STEP_DETAILS           135
#define IDB_BITMAP1                     135
#define IDD_DLG_ADD_FILES               136
#define IDR_MNU_PROJECT                 138
#define IDR_MNU_ACTION                  139
#define IDD_DLG_OPEN_PROJECT            140
#define IDR_MNU_PPAGE_DATA              141
#define IDD_PAGE_OPTIONS                141
#define IDR_MNU_MINIMAL                 142
#define IDD_PAGE_DATA_PROPS             142
#define IDB_BITMAP2                     143
#define IDD_DLG_SPLASH                  144
#define IDD_PAGE_LOGGING                145
#define IDB_BMP_AAH_LOGO                146
#define IDB_BMP_AAH_LOGO_OLD            146
#define IDD_PAGE_LOGGING_ADO            146
#define IDB_BMP_AAH_LOGO_NEW            147
#define IDD_PAGE_DATA                   147
#define IDI_ICON_SUCCESS                148
#define IDI_ICON_WARNING                149
#define IDI_ICON_FAILURE                150
#define IDC_LIST1                       1000
#define IDC_BUTTON1                     1001
#define IDC_CHECK1                      1002
#define IDC_BN_SRC_DIR                  1002
#define IDC_BN_QUICK_HELP               1003
#define IDC_BN_DEST_DIR                 1003
#define IDC_BUTTON3                     1004
#define IDC_BN_SRC_DIR_DEFAULT          1004
#define IDC_BN_DEST_DIR_DEFAULT         1005
#define IDC_LBL_FILEPATH                1006
#define IDC_CHECK2                      1007
#define IDC_BTN_BUILD_LISTNG            1008
#define IDC_BTN_SOURCE                  1010
#define IDC_EDIT_SOURCEDIR              1011
#define IDC_EDIT_DEST_DIR               1012
#define IDC_BTN_FILE_NAME               1013
#define IDC_BTN_BUILD_LIST              1014
#define IDC_BTN_CHECK_ALL               1015
#define IDC_BTN_DEST_DIR                1016
#define IDC_LBL_FILE_NAME               1017
#define IDC_BTN_SCAN_DIR                1018
#define IDC_PROGRESS_ASSEMBLER          1019
#define IDC_PROGRESS_FILE               1020
#define IDC_RED_HELPTEXT                1020
#define IDC_ED_CUR_BATFILE              1021
#define IDC_BN_RUN_BATFILE              1022
#define IDC_LIST_BATFILES               1023
#define IDC_ED_CUR_RESULTSFILE          1024
#define IDC_RDO_IS_10                   1024
#define IDC_BN_OPEN_RSLTS               1025
#define IDC_RDO_IS_12                   1025
#define IDC_ED_CUR_ISHIELD105_PROJECT   1026
#define IDC_BN_LAUNCH_IS                1026
#define IDC_BN_OPEN_IS_PROJECT          1027
#define IDC_LIST_IS_PROJECTS            1027
#define IDC_LIST_IS_MEDIA               1028
#define IDC_RED_RECV                    1028
#define IDC_BN_EXPLORE                  1029
#define IDC_BN_TEST_PIPE                1029
#define IDC_CMBO_PROJECT                1030
#define IDC_LST_PROJECT_ITEMS           1031
#define IDC_BN_COPY_FILES               1032
#define IDC_PRGRS_BATCH                 1033
#define IDC_PRGRS_FILE                  1034
#define IDC_CMBO_STEP_TYPE              1034
#define IDC_BN_NEW_PROJECT              1035
#define IDC_ED_TEXT                     1035
#define IDC_RED_TEXT_SRCFILE            1036
#define IDC_BN_VALIDATE_PROJECT         1036
#define IDC_ED_LABEL_SRCFILE            1037
#define IDC_BN_SAVE_AS                  1037
#define IDC_RED_TEXT_SOURCEDIR          1038
#define IDC_BN_PROJECT                  1038
#define IDC_ED_LABEL_SOURCEDIR          1039
#define IDC_BN_ACTION                   1039
#define IDC_RED_TEXT_DESTDIR            1040
#define IDC_BN_SELECT                   1040
#define IDC_ED_LABEL_DESTDIR            1041
#define IDC_BN_FILE_LIST                1041
#define IDC_RED_TEXT_DESTFILE           1042
#define IDC_ED_LABEL_DESTFILE           1043
#define IDC_BN_SRC_FILE                 1044
#define IDC_BN_DEST_FILE                1045
#define IDC_ED_DFLT_SRC_DIR             1045
#define IDC_ED_DFLT_DEST_DIR            1046
#define IDC_BN_BROWSE_DFLT_SRC_DIR      1047
#define IDC_BN_BROWSE_DFLT_DEST_DIR     1048
#define IDC_BN_BROWSE_DIR               1048
#define IDC_ED_PROMPT                   1049
#define IDC_ED_CUR_DIR                  1050
#define IDC_BN_BROWSE                   1051
#define IDC_LIST_CUR_FILES              1052
#define IDC_BN_SEL_ALL                  1053
#define IDC_BN_SEL_NONE                 1054
#define IDC_BN_SEL_INVERT               1055
#define IDC_CHK_LOCK                    1056
#define IDC_STATIC_DFLT_SRC             1057
#define IDC_STATIC_DFLT_DEST            1058
#define IDC_BN_SEL_HIGHLIGHTED          1059
#define IDC_LCTRL_BATFILES              1059
#define IDC_BN_EXPORT_CSV               1060
#define IDC_LCTRL_IS_PROJECTS           1060
#define IDC_LCTRL_IS_MEDIA              1061
#define IDC_LIST_EXIST_PROJECTS         1061
#define IDC_BN_EXPORT_CSV_TICKED        1061
#define IDC_ED_CUR_PROJECT              1062
#define IDC_LIST_DATA_PROPS             1063
#define IDC_ED_ROW_COUNT                1063
#define IDC_BN_ICON                     1065
#define IDC_BN_REFRESH                  1065
#define IDC_LOGO                        1067
#define IDC_RED_BATCH_CONTENTS          1068
#define IDC_LIST_LOG                    1069
#define IDC_LIST_CATEGORIES             1070
#define IDC_RED_LOG_TEXT                1071
#define IDC_RED_LOG_SOURCE              1072
#define IDC_AXSIMPLEDATAGRIDCTRL1       1072
#define IDC_RED_LOG_SQL                 1073
#define IDC_EDIT1                       1073
#define IDC_ED_CLICKED                  1073
#define ID_CTXT_ADDASTEP                32771
#define ID_CTXT_EDITASTEP               32772
#define ID_CTXT_DELETEASTEP             32773
#define ID_CTXT_REORDINATE              32774
#define ID_CTXT_COPYASTEP               32775
#define ID_CTXT_EXPLORESOURCE           32776
#define ID_CTXT_EXPLOREDESTINATION      32777
#define ID_CTXT_ADDSINGLEFILES          32778
#define ID_PROJECT_NEW                  32779
#define ID_PROJECT_SAVEAS               32781
#define ID_PROJECT_DELETE               32782
#define ID_PROJECT_OPEN                 32786
#define ID_ACTION_VALIDATEPROJECT       32789
#define ID_ACTION_COPYPROJECTFILES      32790
#define ID_FILE_EXIT                    32791
#define ID_PROJECT_ARCHIVE_EXPORT       32793
#define ID_PROJECT_ARCHIVE_IMPORT       32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
